// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: earnedskill.sql

package earnedskillQuerier

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getOneByUserID = `-- name: GetOneByUserID :one
SELECT user_id, skills, session_ids, created_at, updated_at FROM earned_skills
WHERE user_id = $1
`

func (q *Queries) GetOneByUserID(ctx context.Context, userID uuid.UUID) (EarnedSkill, error) {
	row := q.db.QueryRowContext(ctx, getOneByUserID, userID)
	var i EarnedSkill
	err := row.Scan(
		&i.UserID,
		pq.Array(&i.Skills),
		pq.Array(&i.SessionIds),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOne = `-- name: UpsertOne :one
INSERT INTO earned_skills (user_id, skills, session_ids, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (user_id) DO UPDATE SET
  skills = EXCLUDED.skills,
  session_ids = EXCLUDED.session_ids,
  updated_at = NOW()
RETURNING user_id, skills, session_ids, created_at, updated_at
`

type UpsertOneParams struct {
	UserID     uuid.UUID
	Skills     []string
	SessionIds []uuid.UUID
}

func (q *Queries) UpsertOne(ctx context.Context, arg UpsertOneParams) (EarnedSkill, error) {
	row := q.db.QueryRowContext(ctx, upsertOne, arg.UserID, pq.Array(arg.Skills), pq.Array(arg.SessionIds))
	var i EarnedSkill
	err := row.Scan(
		&i.UserID,
		pq.Array(&i.Skills),
		pq.Array(&i.SessionIds),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
