// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package earnedskillQuerier

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetOneByUserID(ctx context.Context, userID uuid.UUID) (EarnedSkill, error)
	UpsertOne(ctx context.Context, arg UpsertOneParams) (EarnedSkill, error)
}

var _ Querier = (*Queries)(nil)
