apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: arcgentic
data:
  ENVIRONMENT: production
  LOG_LEVEL: info
  POSTGRES_IS_SSL_DISABLED: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: arcgentic
data:
  AGENT_SERVICE_URL: http://agent-service:5001
  USER_SERVICE_URL: http://user-service:8080
