apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-service-env
  namespace: arcgentic
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: user-service-env
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_URI
      remoteRef:
        key: arcgentic/prod/user-service
        property: POSTGRES_URI
    - secretKey: POSTGRES_DATABASE
      remoteRef:
        key: arcgentic/prod/user-service
        property: POSTGRES_DATABASE
    - secretKey: MIGRATE_DATABASE_URL
      remoteRef:
        key: arcgentic/prod/user-service
        property: MIGRATE_DATABASE_URL
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agent-service-env
  namespace: arcgentic
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: agent-service-env
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: arcgentic/prod/agent-service
        property: DATABASE_URL
  dataFrom:
    - extract:
        key: arcgentic/prod/agent-service
