apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: arcgentic
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-service
  namespace: arcgentic
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: arcgentic
