// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"context"
	"errors"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/introspection"
	"github.com/google/uuid"
	"github.com/smithg09/core/internal/module/earnedskill"
	"github.com/smithg09/core/internal/module/session"
	"github.com/smithg09/core/internal/module/user"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{
		schema:     cfg.Schema,
		resolvers:  cfg.Resolvers,
		directives: cfg.Directives,
		complexity: cfg.Complexity,
	}
}

type Config struct {
	Schema     *ast.Schema
	Resolvers  ResolverRoot
	Directives DirectiveRoot
	Complexity ComplexityRoot
}

type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	EarnedSkills struct {
		CreatedAt  func(childComplexity int) int
		SessionIDs func(childComplexity int) int
		Skills     func(childComplexity int) int
		UpdatedAt  func(childComplexity int) int
		UserID     func(childComplexity int) int
	}

	Mutation struct {
		CreateSession      func(childComplexity int, data session.CreateDto) int
		CreateUser         func(childComplexity int, data user.CreateDto) int
		DeleteUser         func(childComplexity int, id uuid.UUID) int
		UpdateSession      func(childComplexity int, id uuid.UUID, data session.UpdateDto) int
		UpdateUser         func(childComplexity int, id uuid.UUID, data user.UpdateDto) int
		UpsertEarnedSkills func(childComplexity int, data earnedskill.UpsertDto) int
	}

	Query struct {
		GetEarnedSkills    func(childComplexity int, userID uuid.UUID) int
		GetSession         func(childComplexity int, id uuid.UUID) int
		GetUser            func(childComplexity int, id uuid.UUID) int
		ListSessions       func(childComplexity int, where *session.WhereDto) int
		Ping               func(childComplexity int) int
		__resolve__service func(childComplexity int) int
	}

	Session struct {
		CreatedAt         func(childComplexity int) int
		IsMarkedCompleted func(childComplexity int) int
		SessionID         func(childComplexity int) int
		UpdatedAt         func(childComplexity int) int
		UserID            func(childComplexity int) int
	}

	User struct {
		CreatedAt        func(childComplexity int) int
		Email            func(childComplexity int) int
		Id               func(childComplexity int) int
		LlmPreferences   func(childComplexity int) int
		Name             func(childComplexity int) int
		ProfessionalRole func(childComplexity int) int
		UpdatedAt        func(childComplexity int) int
	}

	_Service struct {
		SDL func(childComplexity int) int
	}
}

type executableSchema struct {
	schema     *ast.Schema
	resolvers  ResolverRoot
	directives DirectiveRoot
	complexity ComplexityRoot
}

func (e *executableSchema) Schema() *ast.Schema {
	if e.schema != nil {
		return e.schema
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := executionContext{nil, e, 0, 0, nil}
	_ = ec
	switch typeName + "." + field {

	case "EarnedSkills.created_at":
		if e.complexity.EarnedSkills.CreatedAt == nil {
			break
		}

		return e.complexity.EarnedSkills.CreatedAt(childComplexity), true

	case "EarnedSkills.session_ids":
		if e.complexity.EarnedSkills.SessionIDs == nil {
			break
		}

		return e.complexity.EarnedSkills.SessionIDs(childComplexity), true

	case "EarnedSkills.skills":
		if e.complexity.EarnedSkills.Skills == nil {
			break
		}

		return e.complexity.EarnedSkills.Skills(childComplexity), true

	case "EarnedSkills.updated_at":
		if e.complexity.EarnedSkills.UpdatedAt == nil {
			break
		}

		return e.complexity.EarnedSkills.UpdatedAt(childComplexity), true

	case "EarnedSkills.user_id":
		if e.complexity.EarnedSkills.UserID == nil {
			break
		}

		return e.complexity.EarnedSkills.UserID(childComplexity), true

	case "Mutation.createSession":
		if e.complexity.Mutation.CreateSession == nil {
			break
		}

		args, err := ec.field_Mutation_createSession_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateSession(childComplexity, args["data"].(session.CreateDto)), true

	case "Mutation.createUser":
		if e.complexity.Mutation.CreateUser == nil {
			break
		}

		args, err := ec.field_Mutation_createUser_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateUser(childComplexity, args["data"].(user.CreateDto)), true

	case "Mutation.deleteUser":
		if e.complexity.Mutation.DeleteUser == nil {
			break
		}

		args, err := ec.field_Mutation_deleteUser_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.DeleteUser(childComplexity, args["id"].(uuid.UUID)), true

	case "Mutation.updateSession":
		if e.complexity.Mutation.UpdateSession == nil {
			break
		}

		args, err := ec.field_Mutation_updateSession_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateSession(childComplexity, args["id"].(uuid.UUID), args["data"].(session.UpdateDto)), true

	case "Mutation.updateUser":
		if e.complexity.Mutation.UpdateUser == nil {
			break
		}

		args, err := ec.field_Mutation_updateUser_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateUser(childComplexity, args["id"].(uuid.UUID), args["data"].(user.UpdateDto)), true

	case "Mutation.upsertEarnedSkills":
		if e.complexity.Mutation.UpsertEarnedSkills == nil {
			break
		}

		args, err := ec.field_Mutation_upsertEarnedSkills_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpsertEarnedSkills(childComplexity, args["data"].(earnedskill.UpsertDto)), true

	case "Query.getEarnedSkills":
		if e.complexity.Query.GetEarnedSkills == nil {
			break
		}

		args, err := ec.field_Query_getEarnedSkills_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.GetEarnedSkills(childComplexity, args["user_id"].(uuid.UUID)), true

	case "Query.getSession":
		if e.complexity.Query.GetSession == nil {
			break
		}

		args, err := ec.field_Query_getSession_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.GetSession(childComplexity, args["id"].(uuid.UUID)), true

	case "Query.getUser":
		if e.complexity.Query.GetUser == nil {
			break
		}

		args, err := ec.field_Query_getUser_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.GetUser(childComplexity, args["id"].(uuid.UUID)), true

	case "Query.listSessions":
		if e.complexity.Query.ListSessions == nil {
			break
		}

		args, err := ec.field_Query_listSessions_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.ListSessions(childComplexity, args["where"].(*session.WhereDto)), true

	case "Query.ping":
		if e.complexity.Query.Ping == nil {
			break
		}

		return e.complexity.Query.Ping(childComplexity), true

	case "Query._service":
		if e.complexity.Query.__resolve__service == nil {
			break
		}

		return e.complexity.Query.__resolve__service(childComplexity), true

	case "Session.created_at":
		if e.complexity.Session.CreatedAt == nil {
			break
		}

		return e.complexity.Session.CreatedAt(childComplexity), true

	case "Session.is_marked_completed":
		if e.complexity.Session.IsMarkedCompleted == nil {
			break
		}

		return e.complexity.Session.IsMarkedCompleted(childComplexity), true

	case "Session.session_id":
		if e.complexity.Session.SessionID == nil {
			break
		}

		return e.complexity.Session.SessionID(childComplexity), true

	case "Session.updated_at":
		if e.complexity.Session.UpdatedAt == nil {
			break
		}

		return e.complexity.Session.UpdatedAt(childComplexity), true

	case "Session.user_id":
		if e.complexity.Session.UserID == nil {
			break
		}

		return e.complexity.Session.UserID(childComplexity), true

	case "User.created_at":
		if e.complexity.User.CreatedAt == nil {
			break
		}

		return e.complexity.User.CreatedAt(childComplexity), true

	case "User.email":
		if e.complexity.User.Email == nil {
			break
		}

		return e.complexity.User.Email(childComplexity), true

	case "User.id":
		if e.complexity.User.Id == nil {
			break
		}

		return e.complexity.User.Id(childComplexity), true

	case "User.llm_preferences":
		if e.complexity.User.LlmPreferences == nil {
			break
		}

		return e.complexity.User.LlmPreferences(childComplexity), true

	case "User.name":
		if e.complexity.User.Name == nil {
			break
		}

		return e.complexity.User.Name(childComplexity), true

	case "User.professional_role":
		if e.complexity.User.ProfessionalRole == nil {
			break
		}

		return e.complexity.User.ProfessionalRole(childComplexity), true

	case "User.updated_at":
		if e.complexity.User.UpdatedAt == nil {
			break
		}

		return e.complexity.User.UpdatedAt(childComplexity), true

	case "_Service.sdl":
		if e.complexity._Service.SDL == nil {
			break
		}

		return e.complexity._Service.SDL(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := executionContext{opCtx, e, 0, 0, make(chan graphql.DeferredResult)}
	inputUnmarshalMap := graphql.BuildUnmarshalerMap(
		ec.unmarshalInputCreateSessionDto,
		ec.unmarshalInputCreateUserDto,
		ec.unmarshalInputDateFilter,
		ec.unmarshalInputFloat64Filter,
		ec.unmarshalInputIntFilter,
		ec.unmarshalInputPaginationFilter,
		ec.unmarshalInputSortFilter,
		ec.unmarshalInputStringFilter,
		ec.unmarshalInputUpdateSessionDto,
		ec.unmarshalInputUpdateUserDto,
		ec.unmarshalInputUpsertEarnedSkillsDto,
		ec.unmarshalInputUuidFilter,
		ec.unmarshalInputWhereSessionsDto,
	)
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.pendingDeferred) > 0 {
					result := <-ec.deferredResults
					atomic.AddInt32(&ec.pendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.pendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}
	case ast.Mutation:
		return func(ctx context.Context) *graphql.Response {
			if !first {
				return nil
			}
			first = false
			ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
			data := ec._Mutation(ctx, opCtx.Operation.SelectionSet)
			var buf bytes.Buffer
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.OperationContext
	*executableSchema
	deferred        int32
	pendingDeferred int32
	deferredResults chan graphql.DeferredResult
}

func (ec *executionContext) processDeferredGroup(dg graphql.DeferredGroup) {
	atomic.AddInt32(&ec.pendingDeferred, 1)
	go func() {
		ctx := graphql.WithFreshResponseContext(dg.Context)
		dg.FieldSet.Dispatch(ctx)
		ds := graphql.DeferredResult{
			Path:   dg.Path,
			Label:  dg.Label,
			Result: dg.FieldSet,
			Errors: graphql.GetErrors(ctx),
		}
		// null fields should bubble up
		if dg.FieldSet.Invalids > 0 {
			ds.Result = graphql.Null
		}
		ec.deferredResults <- ds
	}()
}

func (ec *executionContext) introspectSchema() (*introspection.Schema, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapSchema(ec.Schema()), nil
}

func (ec *executionContext) introspectType(name string) (*introspection.Type, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapTypeFromDef(ec.Schema(), ec.Schema().Types[name]), nil
}

var sources = []*ast.Source{
	{Name: "../../../internal/util/graph/schema.graphql", Input: `# Directives
# 

directive @goModel(
	model: String
	models: [String!]
) on OBJECT | INPUT_OBJECT | SCALAR | ENUM | INTERFACE | UNION

directive @goField(
	forceResolver: Boolean
	name: String
  omittable: Boolean
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

directive @goTag(
	key: String!
	value: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

# Scalars
#
scalar Time
scalar Uuid @goModel(model: "github.com/smithg09/core/internal/util/graph/scalar.Uuid")
scalar Json @goModel(model: "github.com/smithg09/core/internal/util/graph/scalar.Json")

# Inputs
# 
input IntFilter @goModel(model: "github.com/smithg09/core/internal/util/filter.IntFilter") {
	"Specifies equality condition. The $eq operator matches documents where the value of a field equals the specified value."
  eq: Int
	"$gt selects those documents where the value of the field is greater than (i.e. >) the specified value."
	gt: Int
	"$gte selects the documents where the value of the field is greater than or equal to (i.e. >=) a specified value (e.g. value.)"
	gte: Int
	"$lt selects the documents where the value of the field is less than (i.e. <) the specified value."
	lt: Int
	"$lte selects the documents where the value of the field is less than or equal to (i.e. <=) the specified value."
	lte: Int
}

input Float64Filter @goModel(model: "github.com/smithg09/core/internal/util/filter.Float64Filter") {
	"Specifies equality condition. The $eq operator matches documents where the value of a field equals the specified value."
  eq: Float
	"$gt selects those documents where the value of the field is greater than (i.e. >) the specified value."
	gt: Float
	"$gte selects the documents where the value of the field is greater than or equal to (i.e. >=) a specified value (e.g. value.)"
	gte: Float
	"$lt selects the documents where the value of the field is less than (i.e. <) the specified value."
	lt: Float
	"$lte selects the documents where the value of the field is less than or equal to (i.e. <=) the specified value."
	lte: Float
}

input DateFilter @goModel(model: "github.com/smithg09/core/internal/util/filter.DateFilter") {
	"Specifies equality condition. The $eq operator matches documents where the value of a field equals the specified value."
  eq: Time
	"$gt selects those documents where the value of the field is greater than (i.e. >) the specified value."
	gt: Time
	"$gte selects the documents where the value of the field is greater than or equal to (i.e. >=) a specified value (e.g. value.)"
	gte: Time
	"$lt selects the documents where the value of the field is less than (i.e. <) the specified value."
	lt: Time
	"$lte selects the documents where the value of the field is less than or equal to (i.e. <=) the specified value."
	lte: Time
}

input StringFilter @goModel(model: "github.com/smithg09/core/internal/util/filter.StringFilter") {
  "Specifies equality condition. The $eq operator matches documents where the value of a field equals the specified value."
  eq: String
  "Specifies a regular expression pattern for matching strings."
  regex: String
}

input UuidFilter @goModel(model: "github.com/smithg09/core/internal/util/filter.UuidFilter") {
  "Specifies equality condition. The $eq operator matches documents where the value of a field equals the specified value."
  eq: Uuid
  "Specifies a list of UUID values. The $in operator matches documents where the value of a field equals any value in the specified list."
  in: [Uuid!]
}

input SortFilter @goModel(model: "github.com/smithg09/core/internal/util/filter.SortFilter") {
  sortBy: String
	sortOrder: SortOrder
}

input PaginationFilter @goModel(model: "github.com/smithg09/core/internal/util/filter.PaginationFilter") {
  limit: Int
	skip: Int
}

# Enums
# 
enum SortOrder @goModel(model: "github.com/smithg09/core/internal/util/filter.SortOrder") {
  asc
	desc
}


# Health check query
# 
extend type Query {
	ping: String
}`, BuiltIn: false},
	{Name: "../../../internal/module/earnedskill/schema.graphql", Input: `type EarnedSkills @goModel(model: "github.com/smithg09/core/internal/module/earnedskill.EarnedSkill") {
  user_id: Uuid! @goField(name: "UserID")
  skills: [String!]!
  session_ids: [Uuid!]! @goField(name: "SessionIDs")
  created_at: Time!
  updated_at: Time!
}

input UpsertEarnedSkillsDto @goModel(model: "github.com/smithg09/core/internal/module/earnedskill.UpsertDto") {
  user_id: Uuid! @goField(name: "UserID")
  skills: [String!]!
  session_ids: [Uuid!]! @goField(name: "SessionIDs")
}

extend type Query {
  getEarnedSkills(user_id: Uuid!): EarnedSkills
}

extend type Mutation {
  upsertEarnedSkills(data: UpsertEarnedSkillsDto!): EarnedSkills
}`, BuiltIn: false},
	{Name: "../../../internal/module/session/schema.graphql", Input: `type Session @goModel(model: "github.com/smithg09/core/internal/module/session.Session") {
  session_id: Uuid! @goField(name: "SessionID")
  user_id: Uuid! @goField(name: "UserID")
  is_marked_completed: Boolean! @goField(name: "IsMarkedCompleted")
  created_at: Time!
  updated_at: Time!
}

input CreateSessionDto @goModel(model: "github.com/smithg09/core/internal/module/session.CreateDto") {
  user_id: Uuid! @goField(name: "UserID")
  is_marked_completed: Boolean @goField(name: "IsMarkedCompleted")
}

input WhereSessionsDto @goModel(model: "github.com/smithg09/core/internal/module/session.WhereDto") {
  user_id: UuidFilter @goField(name: "UserID")
  is_marked_completed: Boolean @goField(name: "IsMarkedCompleted")
  sort: SortFilter
  pagination: PaginationFilter
}

input UpdateSessionDto @goModel(model: "github.com/smithg09/core/internal/module/session.UpdateDto") {
  user_id: Uuid @goField(name: "UserID")
  is_marked_completed: Boolean @goField(name: "IsMarkedCompleted")
}

extend type Query {
  getSession(id: Uuid!): Session
  listSessions(where: WhereSessionsDto): [Session!]!
}

extend type Mutation {
  createSession(data: CreateSessionDto!): Session
  updateSession(id: Uuid!, data: UpdateSessionDto!): Session
}`, BuiltIn: false},
	{Name: "../../../internal/module/user/schema.graphql", Input: `type User @goModel(model: "github.com/smithg09/core/internal/module/user.User") {
  id: Uuid!
  name: String!
  email: String!
  professional_role: String! @goField(name: "ProfessionalRole")
  llm_preferences: String! @goField(name: "LlmPreferences")
  created_at: Time!
  updated_at: Time!
}

input CreateUserDto @goModel(model: "github.com/smithg09/core/internal/module/user.CreateDto") {
  name: String!
  email: String!
  professional_role: String! @goField(name: "ProfessionalRole")
  llm_preferences: String @goField(name: "LlmPreferences")
}

input UpdateUserDto @goModel(model: "github.com/smithg09/core/internal/module/user.UpdateDto") {
  name: String
  email: String
  professional_role: String @goField(name: "ProfessionalRole")
  llm_preferences: String @goField(name: "LlmPreferences")
}

extend type Query {
  getUser(id: Uuid!): User
}

extend type Mutation {
  createUser(data: CreateUserDto!): User
  updateUser(id: Uuid!, data: UpdateUserDto!): User
  deleteUser(id: Uuid!): Boolean
}`, BuiltIn: false},
	{Name: "../../../federation/directives.graphql", Input: `
	directive @key(fields: _FieldSet!) repeatable on OBJECT | INTERFACE
	directive @requires(fields: _FieldSet!) on FIELD_DEFINITION
	directive @provides(fields: _FieldSet!) on FIELD_DEFINITION
	directive @extends on OBJECT | INTERFACE
	directive @external on FIELD_DEFINITION
	scalar _Any
	scalar _FieldSet
`, BuiltIn: true},
	{Name: "../../../federation/entity.graphql", Input: `
type _Service {
  sdl: String
}

extend type Query {
  _service: _Service!
}
`, BuiltIn: true},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)
