package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/google/uuid"
	"github.com/smithg09/core/internal/module/earnedskill"
	"github.com/smithg09/core/internal/module/session"
	"github.com/smithg09/core/internal/module/user"
)

// UpsertEarnedSkills is the resolver for the upsertEarnedSkills field.
func (r *mutationResolver) UpsertEarnedSkills(ctx context.Context, data earnedskill.UpsertDto) (*earnedskill.EarnedSkill, error) {
	return r.EarnedSkillService.UpsertEarnedSkills(ctx, data)
}

// CreateSession is the resolver for the createSession field.
func (r *mutationResolver) CreateSession(ctx context.Context, data session.CreateDto) (*session.Session, error) {
	return r.SessionService.CreateSession(ctx, data)
}

// UpdateSession is the resolver for the updateSession field.
func (r *mutationResolver) UpdateSession(ctx context.Context, id uuid.UUID, data session.UpdateDto) (*session.Session, error) {
	return r.SessionService.UpdateSession(ctx, id, data)
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, data user.CreateDto) (*user.User, error) {
	return r.UserService.CreateUser(ctx, data)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uuid.UUID, data user.UpdateDto) (*user.User, error) {
	return r.UserService.UpdateUser(ctx, id, data)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id uuid.UUID) (*bool, error) {
	err := r.UserService.DeleteUser(ctx, id)
	if err != nil {
		return nil, err
	}

	success := true
	return &success, nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (*string, error) {
	rtrStr := "Pong!"
	return &rtrStr, nil
}

// GetEarnedSkills is the resolver for the getEarnedSkills field.
func (r *queryResolver) GetEarnedSkills(ctx context.Context, userID uuid.UUID) (*earnedskill.EarnedSkill, error) {
	return r.EarnedSkillService.GetEarnedSkills(ctx, userID)
}

// GetSession is the resolver for the getSession field.
func (r *queryResolver) GetSession(ctx context.Context, id uuid.UUID) (*session.Session, error) {
	return r.SessionService.GetSession(ctx, id)
}

// ListSessions is the resolver for the listSessions field.
func (r *queryResolver) ListSessions(ctx context.Context, where *session.WhereDto) ([]session.Session, error) {
	return r.SessionService.ListSessions(ctx, where)
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id uuid.UUID) (*user.User, error) {
	return r.UserService.GetUser(ctx, id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateCategory(ctx context.Context, data category.CreateDto) (*category.Category, error) {
	return r.CategoryService.CreateCategory(ctx, data)
}
func (r *mutationResolver) UpdateCategory(ctx context.Context, id uuid.UUID, data category.UpdateDto) (*category.Category, error) {
	return r.CategoryService.UpdateCategory(ctx, id, data)
}
func (r *mutationResolver) DeleteCategory(ctx context.Context, id uuid.UUID) (*bool, error) {
	err := r.CategoryService.DeleteCategory(ctx, id)
	if err != nil {
		return nil, err
	}

	success := true
	return &success, nil
}
func (r *mutationResolver) CreatePost(ctx context.Context, data post.CreateDto) (*post.Post, error) {
	return r.PostService.CreatePost(ctx, data)
}
func (r *mutationResolver) UpdatePost(ctx context.Context, id uuid.UUID, data post.UpdateDto) (*post.Post, error) {
	return r.PostService.UpdatePost(ctx, id, data)
}
func (r *mutationResolver) DeletePost(ctx context.Context, id uuid.UUID) (*bool, error) {
	err := r.PostService.DeletePost(ctx, id)
	if err != nil {
		return nil, err
	}

	success := true
	return &success, nil
}
func (r *postResolver) Category(ctx context.Context, obj *post.Post) (*category.Category, error) {
	return r.CategoryService.LoadCategory(ctx, obj.Category)
}
func (r *queryResolver) GetCategory(ctx context.Context, id uuid.UUID) (*category.Category, error) {
	return r.CategoryService.GetCategory(ctx, id)
}
func (r *queryResolver) ListCategories(ctx context.Context, where *category.WhereDto) ([]category.Category, error) {
	return r.CategoryService.ListCategories(ctx, where)
}
func (r *queryResolver) GetPost(ctx context.Context, id uuid.UUID) (*post.Post, error) {
	return r.PostService.GetPost(ctx, id)
}
func (r *queryResolver) ListPosts(ctx context.Context, where *post.WhereDto) ([]post.Post, error) {
	return r.PostService.ListPosts(ctx, where)
}
func (r *Resolver) Post() PostResolver { return &postResolver{r} }
type postResolver struct{ *Resolver }
*/
