// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sessionQuerier

import (
	"time"

	"github.com/google/uuid"
)

type EarnedSkill struct {
	UserID     uuid.UUID
	Skills     []string
	SessionIds []uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Session struct {
	SessionID         uuid.UUID
	UserID            uuid.UUID
	IsMarkedCompleted bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Title             string
	IsArchived        bool
}

type User struct {
	ID               uuid.UUID
	Name             string
	Email            string
	ProfessionalRole string
	LlmPreferences   string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
