// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sessionQuerier

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOne(ctx context.Context, arg CreateOneParams) (Session, error)
	GetMany(ctx context.Context, arg GetManyParams) ([]Session, error)
	GetOneById(ctx context.Context, sessionID uuid.UUID) (Session, error)
	UpdateOneById(ctx context.Context, arg UpdateOneByIdParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
