// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session.sql

package sessionQuerier

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createOne = `-- name: CreateOne :one
INSERT INTO sessions (user_id, title, is_marked_completed, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING session_id, user_id, is_marked_completed, created_at, updated_at, title
`

type CreateOneParams struct {
	UserID            uuid.UUID
	Title             string
	IsMarkedCompleted bool
}

func (q *Queries) CreateOne(ctx context.Context, arg CreateOneParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createOne, arg.UserID, arg.Title, arg.IsMarkedCompleted)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.IsMarkedCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return i, err
}

const getMany = `-- name: GetMany :many
SELECT session_id, user_id, is_marked_completed, created_at, updated_at, title
FROM sessions
WHERE
  (
    ($1::uuid IS NOT NULL AND user_id = $1)
    OR
    ($1::uuid IS NULL)
  )
  AND
  (
    (array_length($2::uuid[], 1) > 0 AND user_id = ANY($2::uuid[]))
    OR
    (array_length($2::uuid[], 1) IS NULL)
  )
  AND
  (
    is_marked_completed = $3 OR $3 IS NULL
  )
ORDER BY
  CASE WHEN $4::text = 'created_at__asc' THEN created_at END ASC,
  CASE WHEN $4::text = 'created_at__desc' THEN created_at END DESC,
  CASE WHEN $4::text = 'updated_at__asc' THEN updated_at END ASC,
  CASE WHEN $4::text = 'updated_at__desc' THEN updated_at END DESC,
  CASE WHEN $4::text = 'is_marked_completed__asc' THEN is_marked_completed END ASC,
  CASE WHEN $4::text = 'is_marked_completed__desc' THEN is_marked_completed END DESC
LIMIT $6 OFFSET $5
`

type GetManyParams struct {
	UserIDEq          uuid.NullUUID
	UserIDIn          []uuid.UUID
	IsMarkedCompleted sql.NullBool
	SortQuery         sql.NullString
	Offset            sql.NullInt32
	Limit             sql.NullInt32
}

func (q *Queries) GetMany(ctx context.Context, arg GetManyParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getMany,
		arg.UserIDEq,
		pq.Array(arg.UserIDIn),
		arg.IsMarkedCompleted,
		arg.SortQuery,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.IsMarkedCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneById = `-- name: GetOneById :one
SELECT session_id, user_id, is_marked_completed, created_at, updated_at, title FROM sessions
WHERE session_id = $1
`

func (q *Queries) GetOneById(ctx context.Context, sessionID uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getOneById, sessionID)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.IsMarkedCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return i, err
}

const updateOneById = `-- name: UpdateOneById :one
UPDATE sessions SET
  user_id = coalesce($1, user_id),
  title = coalesce($2, title),
  is_marked_completed = coalesce($3, is_marked_completed),
  updated_at = now()
WHERE session_id = $4 RETURNING session_id, user_id, is_marked_completed, created_at, updated_at, title
`

type UpdateOneByIdParams struct {
	UserID            uuid.NullUUID
	Title             sql.NullString
	IsMarkedCompleted sql.NullBool
	ID                uuid.UUID
}

func (q *Queries) UpdateOneById(ctx context.Context, arg UpdateOneByIdParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateOneById,
		arg.UserID,
		arg.Title,
		arg.IsMarkedCompleted,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.IsMarkedCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return i, err
}
