// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package userQuerier

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Status    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type EarnedSkill struct {
	UserID     uuid.UUID
	Skills     []string
	SessionIds []uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Post struct {
	ID        uuid.UUID
	Title     string
	Slug      string
	Category  uuid.UUID
	Status    string
	Content   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Session struct {
	SessionID         uuid.UUID
	UserID            uuid.UUID
	IsMarkedCompleted bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type User struct {
	ID               uuid.UUID
	Name             string
	Email            string
	ProfessionalRole string
	LlmPreferences   string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
