// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package userQuerier

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOne(ctx context.Context, arg CreateOneParams) (User, error)
	DeleteOne(ctx context.Context, id uuid.UUID) (int64, error)
	GetOneById(ctx context.Context, id uuid.UUID) (User, error)
	UpdateOneById(ctx context.Context, arg UpdateOneByIdParams) (User, error)
}

var _ Querier = (*Queries)(nil)
