// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package userQuerier

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOne = `-- name: CreateOne :one
INSERT INTO users (name, email, professional_role, llm_preferences, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, name, email, professional_role, llm_preferences, created_at, updated_at
`

type CreateOneParams struct {
	Name             string
	Email            string
	ProfessionalRole string
	LlmPreferences   string
}

func (q *Queries) CreateOne(ctx context.Context, arg CreateOneParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createOne,
		arg.Name,
		arg.Email,
		arg.ProfessionalRole,
		arg.LlmPreferences,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ProfessionalRole,
		&i.LlmPreferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOne = `-- name: DeleteOne :execrows
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteOne(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOne, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAll = `-- name: GetAll :many
SELECT id, name, email, professional_role, llm_preferences, created_at, updated_at FROM users
ORDER BY created_at ASC
`

func (q *Queries) GetAll(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ProfessionalRole,
			&i.LlmPreferences,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneById = `-- name: GetOneById :one
SELECT id, name, email, professional_role, llm_preferences, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetOneById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getOneById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ProfessionalRole,
		&i.LlmPreferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOneById = `-- name: UpdateOneById :one
UPDATE users SET
  name = coalesce($1, name),
  email = coalesce($2, email),
  professional_role = coalesce($3, professional_role),
  llm_preferences = coalesce($4, llm_preferences),
  updated_at = now()
WHERE id = $5 RETURNING id, name, email, professional_role, llm_preferences, created_at, updated_at
`

type UpdateOneByIdParams struct {
	Name             sql.NullString
	Email            sql.NullString
	ProfessionalRole sql.NullString
	LlmPreferences   sql.NullString
	ID               uuid.UUID
}

func (q *Queries) UpdateOneById(ctx context.Context, arg UpdateOneByIdParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateOneById,
		arg.Name,
		arg.Email,
		arg.ProfessionalRole,
		arg.LlmPreferences,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ProfessionalRole,
		&i.LlmPreferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
